### ISSUE TITLE
Shift headings on tab/shift+tab when headings are selected?

### ISSUE THREAD

**Issue by vsinha** [k4a-dev/obsidian-heading-shifter#3]
Would you consider adding this as an option? 

I think the ergonomics are sensible-ish to invoke `Increase Headings` or `Decrease Headings` when hitting tab or shift+tab respectively, in the case that the user has a text selection which includes headings. Probably makes sense as an option in case that collides with others' workflows. Open to any thoughts or discussion and possibly willing to just write the feature

**Comment by k4a-dev** [comment]
`tab` and `shift + tab` seems very natural.

By the way, can multiple plugins share the same key process?
For example, I use `obsidian-outliner` and there is a `Enhance the tab key` setting. If this setting is turned on and the same setting is made for heading-shifter, which of the following processes will be performed?

1. both plugins run
2. only one of the plugins run
3. the processing can be divided into "outliner" for list elements and "heading-shifter" for headings.

(I'm sure I'll understand if I try it.)

In any case, the tab key option is worth adding.

**Comment by k4a-dev** [comment]
I have implemented this feature.
If it is not what you want, please comment.

**Comment by k4a-dev** [comment]
@vsinha  Thanks for the feedback! I'm glad to hear that.

**Comment by lukemt** [comment]
This feature works much better than I thought it would. I find the default tab beavoir of obsidian rather annoying. This is so much better!

Also thank you so much for the plugin anyways!

**Comment by ryanwwest** [comment]
Thanks, this behavior was exactly what I was looking for.
