### ISSUE TITLE
Toggle head

### ISSUE THREAD

**Issue by quanru** [k4a-dev/obsidian-heading-shifter#5]
![image](https://user-images.githubusercontent.com/11739753/186565388-d072f309-8d6f-4a3c-a681-c7040359c17d.png)
when i key down the 'cmd + opt + 1' one more time, it will shift the head to normal text

**Comment by k4a-dev** [comment]
Is this a bug report or feature request?
If it is a bug, please tell me how to reproduce it as it does not occur in my environment.

**Comment by k4a-dev** [comment]
If there are no comments I will close after 12 hours.

**Comment by quanru** [comment]
sorry, it is a feature request~

**Comment by k4a-dev** [comment]
I will not implement that feature.

It is not correct that the same operation changes as follows.
- any heading -> heading 1 -> no heading

The following case looks like a toggle operation, but this is just a coincidence.
- no heading -> heading 1 -> no heading

The following case is not a toggle operation at all.
- heading 4 -> heading 1 -> no heading -> heading 1
